module.exports = {
  // simpleText
  SIMPLE_TEXT_MAX: 1000,

  // textCard
  TEXT_CARD_TEXT_MAX: 400,
  TEXT_CARD_BUTTON_LABEL_MAX: 14,
  TEXT_CARD_BUTTONS_MAX: 3,

  // basicCard
  BASIC_CARD_TITLE_MAX: 40,
  BASIC_CARD_DESCRIPTION_MAX: 400,
  BASIC_CARD_BUTTON_LABEL_MAX: 14,
  BASIC_CARD_BUTTONS_MAX: 3,

  // listCard
  LIST_CARD_HEADER_MAX: 40,
  LIST_CARD_ITEM_TITLE_MAX: 40,
  LIST_CARD_ITEM_DESC_MAX: 60,
  LIST_CARD_ITEMS_MAX: 5,
  LIST_CARD_BUTTONS_MAX: 2,

  // itemCard
  ITEM_CARD_TITLE_MAX: 40,
  ITEM_CARD_DESCRIPTION_MAX: 60,
  ITEM_CARD_ITEMS_MAX: 10,

  // carousel
  CAROUSEL_CARDS_MAX: 10,

  // quickReplies
  QUICK_REPLY_LABEL_MAX: 14,
  QUICK_REPLIES_MAX: 10,
};
